#!/usr/bin/python

from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
HOST=($1)
ssh.connect("$HOST")

with SCPClient(ssh.get_transport()) as scp:
    scp.put("$2")
    
