#!/usr/bin/python

from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect($1)

with SCPClient(ssh.get_transport()) as scp:
    scp.put($2)
    
